# Generated by Django 5.0.7 on 2024-12-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=65)),
                ('descricao', models.TextField()),
                ('link', models.TextField()),
                ('tipo', models.CharField(choices=[('video', 'Vídeo'), ('imagem', 'Imagem')], max_length=10)),
                ('capa_img', models.ImageField(upload_to='capa/imagem/%Y/%m/%d/')),
                ('capa_video', models.FileField(upload_to='capa/video/%Y/%m/%d/')),
                ('github', models.TextField()),
                ('executaveis', models.FileField(blank=True, null=True, upload_to='executaveis/%Y/%m/%d/')),
            ],
        ),
    ]
