# Generated by Django 5.0.7 on 2024-12-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_alter_projeto_capa_img_alter_projeto_capa_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='capa_video',
            field=models.FileField(blank=True, null=True, upload_to='capa_video/video/%Y/%m/%d/'),
        ),
    ]
