# Generated by Django 5.0.7 on 2024-12-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_projeto_capa_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='capa_video',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='tipo',
        ),
    ]
