# Generated by Django 5.0.7 on 2024-12-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_remove_projeto_capa_video_remove_projeto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='capa_video',
            field=models.FileField(blank=True, null=True, upload_to='capa/video/%Y/%m/%d/'),
        ),
    ]
