# Generated by Django 5.0.7 on 2024-12-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_remove_projeto_executaveis_projeto_apk_projeto_exe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='category',
            field=models.ManyToManyField(to='projetos.category'),
        ),
    ]
